### ISSUE TITLE
Graph of issue tracker

### ISSUE THREAD

**Issue by davelab6** [notofonts/notobuilder#2]
I'd like a graph like this, which runs on some frequency (e.g. weekly) and is shown on this repo's README (and later perhaps in https://github.com/notofonts/noto-docs or so)

![Screenshot_20200610_112100](https://user-images.githubusercontent.com/261579/112195295-2c791500-8be0-11eb-881b-979e51d5418d.png)

(from https://valdyas.org/fading/hacking/krita-hacking/nightmares-and-bugs/)

**Comment by simoncozens** [comment]
This is at https://notofonts.github.io/analytics.html
