### ISSUE TITLE
Reduce clutter by having fewer fonts?

### ISSUE THREAD

**Issue by allefeld** [notofonts/notobuilder#20]
I think it's great that you have created a huge font family which covers all scripts/writing systems defined in Unicode 6.1, and are still working to expand coverage. Though I can't read anything beyond the latin script (and a tiny bit of Greek), I like having the Noto fonts installed on my computer, so that when I encounter e.g. a website in a non-latin script, it's not just a bunch of boxes.

However, a serious drawback of that is the clutter it creates in font menus. I'm on Debian 11, and I currently have only `fonts-noto-core`, `fonts-noto-mono` and `fonts-noto-color-emoji` installed, and I still have 193 entries in my font selection list!

Now I understand the point made in the FAQ that there is a limitation to the number of glyphs in a font. However, according to the list on [Wikipedia](https://en.wikipedia.org/wiki/Noto_fonts#List_of_Noto_fonts), there are many Noto fonts which contain only a few hundred, or even a few dozen glyphs. So it should be possible to reduce the number of fonts considerably, e.g. by combining a number of linguistically or geographically related scripts into a single font. The FAQ states that there is a plan to do so

> However, we are working on a possible repackaging of the fonts into a few files.

but if I'm not mistaken that entry is 5 years old. Does this plan still exist?

**Comment by allefeld** [comment]
@simoncozens Is there an update to this?

**Comment by simoncozens** [comment]
We have the full builds working now and they're part of the releases, but I still haven't thought of a better way to segment the fonts without being discriminatory. OTOH, we have also introduced (for development/release staging purposes only) the concept of Noto "tiers" from 1-5, so maybe that bridge is already crossed. I should experiment to see if we could put all of each tier into a single font. There are some technological investigations around the idea of raising the glyph limit which may mean we can combine all of Noto into one font, but that'll be a way off.

**Comment by allefeld** [comment]
@simoncozens, just checking in :)

I'm not sure I understand the problem of being discriminatory. I'm not an expert (at all), but [Wikipedia](https://en.wikipedia.org/wiki/List_of_writing_systems) has a table with four families of writing systems (Abjad, Abugida, Alphabetic, Logographic & Syllabic), where each family contains from 2 to 9 subfamilies:
![image](https://github.com/user-attachments/assets/e6a00811-f017-49f2-b0c9-2c4d7fa6f68a)
The article itself contains more extensive lists for each family.

Wouldn't that be a starting point? Or do you expect a user of the Devanagari script would be offended by it being grouped together with the Burmese script? Or a user of the Hebrew script by it being classified as Abjad rather than Alphabetic? And if yes, what is the basis of such an expectation?

**Comment by simoncozens** [comment]
We now produce "mega-merged" versions of Noto Living and Noto Historical at https://github.com/notofonts/notofonts.github.io/tree/main/megamerge.
