### ISSUE TITLE
Tag notobuilder releases

### ISSUE THREAD

**Issue by moyogo** [notofonts/notobuilder#27]
Some changes to notobuilder mean a version of notobuilder cannot be used to build a noto font the same way or at all

It would be nice to have git tags and to use them in Noto repostiries.

For example noto/devanagari now has .glyphspackage sources and notobuilder should be changed accordingly but that would make it hard to rebuild a previous version if one wanted to.

**Comment by simoncozens** [comment]
I think you should always be using the master version of notobuilder to build anything. I'm not sure it makes sense to go back to previous versions.

**Comment by moyogo** [comment]
latin-greek-cyrillic cannot be built at the moment because notobuilder and devanagari are not pinned down.

**Comment by moyogo** [comment]
> It's not quite that.

What do you mean?
